language: java

jdk:
    - openjdk8
    - openjdk7

# Handle gradle cache peculiarity (https://docs.travis-ci.com/user/languages/java#Projects-Using-Gradle)
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  
before_script:
  - gradle wrapper --gradle-version 5.0
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# safelist
branches:
  only:
  - master

dist: trusty
